export const TASKS_GET_TASKS_REQUEST = 'TASKS_GET_TASKS_REQUEST';
export const TASKS_GET_TASKS_SUCCESS = 'TASKS_GET_TASKS_SUCCESS';
export const TASKS_GET_TASKS_FAILURE = 'TASKS_GET_TASKS_FAILURE';
export const TASKS_CREATE_TASK_REQUEST = 'TASKS_CREATE_TASK_REQUEST';
export const TASKS_CREATE_TASK_SUCCESS = 'TASKS_CREATE_TASK_SUCCESS';
export const TASKS_CREATE_TASK_FAILURE = 'TASKS_CREATE_TASK_FAILURE';
